export const themeOverrides = {
  "Card": {
    "closeColorHover": "rgba(0, 0, 0, 0)",
    "closeColorPressed": "rgba(0, 0, 0, 0)",
    "paddingMedium": "0",
    "titleFontSizeMedium": "24px",
    "borderRadius": "15px"
  },
  "Button": {
    "rippleColorPrimary": "#18a058",
    "colorPrimary": "#007AFFFF",
    "borderRadiusMedium": "8px",
    "colorHoverPrimary": "#0088FFFF",
    "colorPressedPrimary": "#007BFFFF",
    "colorFocusPrimary": "#007BFFFF",
    "colorDisabledPrimary": "#007BFFFF",
    "textColorGhostPrimary": "#18a058",
    "borderPrimary": "0",
    "borderPressedPrimary": "0",
    "borderHoverPrimary": "0",
    "borderFocusPrimary": "0",
    "textColorTextPrimary": "#18a058",
    "textColorTextHoverPrimary": "#36ad6a",
    "textColorTextPressedPrimary": "#0c7a43",
    "textColorGhostHoverPrimary": "#36ad6a",
    "textColorGhostPressedPrimary": "#0c7a43",
    "textColorGhostFocusPrimary": "#36ad6a",
    "textColorGhostDisabledPrimary": "#18a058",
    "textColorTextFocusPrimary": "#36ad6a",
    "textColorTextDisabledPrimary": "rgb(51, 54, 57)",
    "textColorHover": "#36ad6a",
    "textColorPressed": "#0c7a43",
    "textColorFocus": "#36ad6a",
    "textColorTextHover": "#36ad6a",
    "textColorTextPressed": "#0c7a43",
    "textColorTextFocus": "#36ad6a",
    "textColorGhostHover": "#36ad6a",
    "textColorGhostPressed": "#0c7a43",
    "textColorGhostFocus": "#36ad6a",
    "rippleColor": "#18a058",
    "colorSuccess": "#18a058",
    "colorHoverSuccess": "#36ad6a",
    "colorPressedSuccess": "#0c7a43",
    "colorFocusSuccess": "#36ad6a",
    "colorDisabledSuccess": "#18a058",
    "textColorTextSuccess": "#18a058",
    "textColorTextHoverSuccess": "#36ad6a",
    "textColorTextPressedSuccess": "#0c7a43",
    "textColorTextFocusSuccess": "#36ad6a",
    "textColorGhostSuccess": "#18a058",
    "textColorGhostHoverSuccess": "#36ad6a",
    "textColorGhostPressedSuccess": "#0c7a43",
    "textColorGhostFocusSuccess": "#36ad6a",
    "textColorGhostDisabledSuccess": "#18a058",
    "rippleColorSuccess": "#18a058",
    "rippleColorError": "#d03050",
    "rippleColorWarning": "#f0a020",
    "rippleColorInfo": "#2080f0",
    "rippleDuration": "0"
  },
  "Spin": {
    "color": "#007AFFFF"
  },
  "Typography": {
    "headerMargin2": "0"
  },
  "Input": {
    "color": "rgba(250, 250, 250, 1)",
    "colorFocus": "rgba(250, 250, 250, 1)"
  }
};